// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: pb/FulcrumService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CityNewNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planet    string `protobuf:"bytes,1,opt,name=Planet,proto3" json:"Planet,omitempty"`
	City      string `protobuf:"bytes,2,opt,name=City,proto3" json:"City,omitempty"`
	Survivors int32  `protobuf:"varint,3,opt,name=Survivors,proto3" json:"Survivors,omitempty"`
}

func (x *CityNewNumber) Reset() {
	*x = CityNewNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_FulcrumService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityNewNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityNewNumber) ProtoMessage() {}

func (x *CityNewNumber) ProtoReflect() protoreflect.Message {
	mi := &file_pb_FulcrumService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityNewNumber.ProtoReflect.Descriptor instead.
func (*CityNewNumber) Descriptor() ([]byte, []int) {
	return file_pb_FulcrumService_proto_rawDescGZIP(), []int{0}
}

func (x *CityNewNumber) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *CityNewNumber) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityNewNumber) GetSurvivors() int32 {
	if x != nil {
		return x.Survivors
	}
	return 0
}

type CityNewName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planet  string `protobuf:"bytes,1,opt,name=Planet,proto3" json:"Planet,omitempty"`
	City    string `protobuf:"bytes,2,opt,name=City,proto3" json:"City,omitempty"`
	NewName string `protobuf:"bytes,3,opt,name=NewName,proto3" json:"NewName,omitempty"`
}

func (x *CityNewName) Reset() {
	*x = CityNewName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_FulcrumService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityNewName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityNewName) ProtoMessage() {}

func (x *CityNewName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_FulcrumService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityNewName.ProtoReflect.Descriptor instead.
func (*CityNewName) Descriptor() ([]byte, []int) {
	return file_pb_FulcrumService_proto_rawDescGZIP(), []int{1}
}

func (x *CityNewName) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *CityNewName) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityNewName) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type CityDelete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Planet    string `protobuf:"bytes,1,opt,name=Planet,proto3" json:"Planet,omitempty"`
	City      string `protobuf:"bytes,2,opt,name=City,proto3" json:"City,omitempty"`
	Survivors int32  `protobuf:"varint,3,opt,name=Survivors,proto3" json:"Survivors,omitempty"`
}

func (x *CityDelete) Reset() {
	*x = CityDelete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_FulcrumService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityDelete) ProtoMessage() {}

func (x *CityDelete) ProtoReflect() protoreflect.Message {
	mi := &file_pb_FulcrumService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityDelete.ProtoReflect.Descriptor instead.
func (*CityDelete) Descriptor() ([]byte, []int) {
	return file_pb_FulcrumService_proto_rawDescGZIP(), []int{2}
}

func (x *CityDelete) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *CityDelete) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityDelete) GetSurvivors() int32 {
	if x != nil {
		return x.Survivors
	}
	return 0
}

type City struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Planet    string `protobuf:"bytes,2,opt,name=Planet,proto3" json:"Planet,omitempty"`
	Survivors int32  `protobuf:"varint,3,opt,name=Survivors,proto3" json:"Survivors,omitempty"`
	Reloj     string `protobuf:"bytes,4,opt,name=Reloj,proto3" json:"Reloj,omitempty"`
	Error     bool   `protobuf:"varint,5,opt,name=Error,proto3" json:"Error,omitempty"`
	Server    string `protobuf:"bytes,6,opt,name=Server,proto3" json:"Server,omitempty"`
}

func (x *City) Reset() {
	*x = City{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_FulcrumService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *City) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*City) ProtoMessage() {}

func (x *City) ProtoReflect() protoreflect.Message {
	mi := &file_pb_FulcrumService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use City.ProtoReflect.Descriptor instead.
func (*City) Descriptor() ([]byte, []int) {
	return file_pb_FulcrumService_proto_rawDescGZIP(), []int{3}
}

func (x *City) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *City) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *City) GetSurvivors() int32 {
	if x != nil {
		return x.Survivors
	}
	return 0
}

func (x *City) GetReloj() string {
	if x != nil {
		return x.Reloj
	}
	return ""
}

func (x *City) GetError() bool {
	if x != nil {
		return x.Error
	}
	return false
}

func (x *City) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nplanet string `protobuf:"bytes,1,opt,name=nplanet,proto3" json:"nplanet,omitempty"`
	Ncity   string `protobuf:"bytes,2,opt,name=ncity,proto3" json:"ncity,omitempty"`
}

func (x *Read) Reset() {
	*x = Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_FulcrumService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_pb_FulcrumService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_pb_FulcrumService_proto_rawDescGZIP(), []int{4}
}

func (x *Read) GetNplanet() string {
	if x != nil {
		return x.Nplanet
	}
	return ""
}

func (x *Read) GetNcity() string {
	if x != nil {
		return x.Ncity
	}
	return ""
}

var File_pb_FulcrumService_proto protoreflect.FileDescriptor

var file_pb_FulcrumService_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x62, 0x2f, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x0d, 0x43, 0x69, 0x74,
	0x79, 0x4e, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x6e,
	0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76,
	0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x75, 0x72, 0x76, 0x69,
	0x76, 0x6f, 0x72, 0x73, 0x22, 0x53, 0x0a, 0x0b, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x65, 0x77, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x56, 0x0a, 0x0a, 0x43, 0x69, 0x74,
	0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43,
	0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x6f, 0x72, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76, 0x6f, 0x72,
	0x73, 0x22, 0x94, 0x01, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x75, 0x72, 0x76, 0x69, 0x76,
	0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x75, 0x72, 0x76, 0x69,
	0x76, 0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x52, 0x65, 0x6c, 0x6f, 0x6a, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x52, 0x65, 0x6c, 0x6f, 0x6a, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x36, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x6e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x63, 0x69, 0x74, 0x79,
	0x32, 0xb1, 0x01, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x19, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x43, 0x69, 0x74, 0x79, 0x12, 0x05, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x1a, 0x05,
	0x2e, 0x43, 0x69, 0x74, 0x79, 0x22, 0x00, 0x12, 0x23, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0c, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x65, 0x77, 0x4e,
	0x61, 0x6d, 0x65, 0x1a, 0x05, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x0c,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x4e, 0x65, 0x77, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x05, 0x2e, 0x43,
	0x69, 0x74, 0x79, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x69, 0x74, 0x79, 0x12, 0x0b, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x1a, 0x05, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x22, 0x00, 0x12, 0x19, 0x0a, 0x07, 0x52, 0x65, 0x61,
	0x64, 0x41, 0x6c, 0x6c, 0x12, 0x05, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x1a, 0x05, 0x2e, 0x43, 0x69,
	0x74, 0x79, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_FulcrumService_proto_rawDescOnce sync.Once
	file_pb_FulcrumService_proto_rawDescData = file_pb_FulcrumService_proto_rawDesc
)

func file_pb_FulcrumService_proto_rawDescGZIP() []byte {
	file_pb_FulcrumService_proto_rawDescOnce.Do(func() {
		file_pb_FulcrumService_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_FulcrumService_proto_rawDescData)
	})
	return file_pb_FulcrumService_proto_rawDescData
}

var file_pb_FulcrumService_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_FulcrumService_proto_goTypes = []interface{}{
	(*CityNewNumber)(nil), // 0: CityNewNumber
	(*CityNewName)(nil),   // 1: CityNewName
	(*CityDelete)(nil),    // 2: CityDelete
	(*City)(nil),          // 3: City
	(*Read)(nil),          // 4: Read
}
var file_pb_FulcrumService_proto_depIdxs = []int32{
	3, // 0: Fulcrum.AddCity:input_type -> City
	1, // 1: Fulcrum.UpdateName:input_type -> CityNewName
	0, // 2: Fulcrum.UpdateNumber:input_type -> CityNewNumber
	2, // 3: Fulcrum.DeleteCity:input_type -> CityDelete
	4, // 4: Fulcrum.ReadAll:input_type -> Read
	3, // 5: Fulcrum.AddCity:output_type -> City
	3, // 6: Fulcrum.UpdateName:output_type -> City
	3, // 7: Fulcrum.UpdateNumber:output_type -> City
	3, // 8: Fulcrum.DeleteCity:output_type -> City
	3, // 9: Fulcrum.ReadAll:output_type -> City
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_FulcrumService_proto_init() }
func file_pb_FulcrumService_proto_init() {
	if File_pb_FulcrumService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_FulcrumService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityNewNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_FulcrumService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityNewName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_FulcrumService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityDelete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_FulcrumService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*City); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_FulcrumService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_FulcrumService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_FulcrumService_proto_goTypes,
		DependencyIndexes: file_pb_FulcrumService_proto_depIdxs,
		MessageInfos:      file_pb_FulcrumService_proto_msgTypes,
	}.Build()
	File_pb_FulcrumService_proto = out.File
	file_pb_FulcrumService_proto_rawDesc = nil
	file_pb_FulcrumService_proto_goTypes = nil
	file_pb_FulcrumService_proto_depIdxs = nil
}
